using System;
using System.Collections.Generic;
using DemoWebApi.Models;

namespace DemoWebApi.Repositories
{
    public class PersonRepository : IPersonRepository
    {
        private readonly List<Person> _people = new List<Person> {
	        new Person { FirstName = "Chester", LastName = "Wise", DateOfBirth = DateTime.Parse("02/08/79"), StreetAddress = "4768 Malesuada Street", City = "Denver", State = "CO", ZipCode = 34696 },
	        new Person { FirstName = "Halee", LastName = "Logan", DateOfBirth = DateTime.Parse("06/29/77"), StreetAddress = "Ap #349-8583 Fermentum Av.", City = "Sacramento", State = "CA", ZipCode = 95415 },
	        new Person { FirstName = "Yardley", LastName = "Lindsey", DateOfBirth = DateTime.Parse("07/22/83"), StreetAddress = "Ap #471-2883 Tincidunt Street", City = "Orlando", State = "FL", ZipCode = 27954 },
	        new Person { FirstName = "Christine", LastName = "Mendez", DateOfBirth = DateTime.Parse("09/11/92"), StreetAddress = "418-8034 Faucibus. Avenue", City = "Billings", State = "MT", ZipCode = 36450 },
	        new Person { FirstName = "Jin", LastName = "Britt", DateOfBirth = DateTime.Parse("08/20/90"), StreetAddress = "296-4624 Lorem Street", City = "San Antonio", State = "TX", ZipCode = 66915 },
	        new Person { FirstName = "Jade", LastName = "Lee", DateOfBirth = DateTime.Parse("06/10/91"), StreetAddress = "3710 Semper St.", City = "Newport News", State = "VA", ZipCode = 72029 },
	        new Person { FirstName = "Rooney", LastName = "Suarez", DateOfBirth = DateTime.Parse("08/02/83"), StreetAddress = "P.O. Box 349, 6091 Aliquet. Rd.", City = "Boise", State = "ID", ZipCode = 15375 },
	        new Person { FirstName = "Amela", LastName = "Goodwin", DateOfBirth = DateTime.Parse("05/07/72"), StreetAddress = "5073 Montes, Ave", City = "Boston", State = "MA", ZipCode = 97682 },
	        new Person { FirstName = "Eleanor", LastName = "Barrera", DateOfBirth = DateTime.Parse("04/24/87"), StreetAddress = "7904 Vehicula Ave", City = "Chandler", State = "AZ", ZipCode = 86197 },
	        new Person { FirstName = "Coby", LastName = "Wilkins", DateOfBirth = DateTime.Parse("12/20/81"), StreetAddress = "452-6244 Lobortis. Rd.", City = "Springfield", State = "MO", ZipCode = 28725 },
	        new Person { FirstName = "Burke", LastName = "Curtis", DateOfBirth = DateTime.Parse("04/21/81"), StreetAddress = "127-1935 Donec Avenue", City = "Philadelphia", State = "PA", ZipCode = 83946 },
	        new Person { FirstName = "Jacob", LastName = "Mcmillan", DateOfBirth = DateTime.Parse("03/15/73"), StreetAddress = "210-3400 A Street", City = "South Portland", State = "ME", ZipCode = 69728 },
	        new Person { FirstName = "Wade", LastName = "Riley", DateOfBirth = DateTime.Parse("10/18/85"), StreetAddress = "Ap #799-3633 Tristique Avenue", City = "Hillsboro", State = "OR", ZipCode = 67071 },
	        new Person { FirstName = "Melyssa", LastName = "Jensen", DateOfBirth = DateTime.Parse("11/17/92"), StreetAddress = "467-2213 Cras St.", City = "Bowling Green", State = "KY", ZipCode = 12283 },
	        new Person { FirstName = "Graiden", LastName = "Sanford", DateOfBirth = DateTime.Parse("08/15/85"), StreetAddress = "P.O. Box 946, 9593 Nec Road", City = "Frederick", State = "MD", ZipCode = 38160 },
	        new Person { FirstName = "Graiden", LastName = "Dean", DateOfBirth = DateTime.Parse("11/19/73"), StreetAddress = "Ap #724-8154 Parturient Rd.", City = "Huntsville", State = "AL", ZipCode = 35832 },
	        new Person { FirstName = "Doris", LastName = "Roberson", DateOfBirth = DateTime.Parse("03/04/71"), StreetAddress = "9816 Nec Rd.", City = "San Jose", State = "CA", ZipCode = 95117 },
	        new Person { FirstName = "Audra", LastName = "Mccullough", DateOfBirth = DateTime.Parse("08/24/78"), StreetAddress = "Ap #592-8041 Ut Rd.", City = "San Antonio", State = "TX", ZipCode = 43165 },
	        new Person { FirstName = "Colin", LastName = "Parrish", DateOfBirth = DateTime.Parse("09/29/74"), StreetAddress = "P.O. Box 856, 4570 Nonummy Av.", City = "Cedar Rapids", State = "IA", ZipCode = 98195 },
	        new Person { FirstName = "Graham", LastName = "Hensley", DateOfBirth = DateTime.Parse("05/05/70"), StreetAddress = "P.O. Box 975, 4110 Dolor. Ave", City = "Sacramento", State = "CA", ZipCode = 94191 },
	        new Person { FirstName = "Karly", LastName = "Larsen", DateOfBirth = DateTime.Parse("02/15/72"), StreetAddress = "P.O. Box 497, 4112 Rutrum Rd.", City = "Rockford", State = "IL", ZipCode = 24139 },
	        new Person { FirstName = "Colton", LastName = "Wells", DateOfBirth = DateTime.Parse("06/27/84"), StreetAddress = "164-7509 Nascetur Av.", City = "Hilo", State = "HI", ZipCode = 92435 },
	        new Person { FirstName = "Vladimir", LastName = "Graham", DateOfBirth = DateTime.Parse("03/30/73"), StreetAddress = "Ap #634-9117 A, St.", City = "Columbia", State = "MO", ZipCode = 43419 },
	        new Person { FirstName = "Abraham", LastName = "Valentine", DateOfBirth = DateTime.Parse("04/29/70"), StreetAddress = "9049 Lacinia St.", City = "Davenport", State = "IA", ZipCode = 16414 },
	        new Person { FirstName = "Kevin", LastName = "Finch", DateOfBirth = DateTime.Parse("01/20/79"), StreetAddress = "Ap #887-7164 Libero. Ave", City = "Saint Louis", State = "MO", ZipCode = 25504 },
	        new Person { FirstName = "David", LastName = "Glover", DateOfBirth = DateTime.Parse("02/14/93"), StreetAddress = "Ap #446-1501 A, Street", City = "Mesa", State = "AZ", ZipCode = 85403 },
	        new Person { FirstName = "Galena", LastName = "Brown", DateOfBirth = DateTime.Parse("12/23/94"), StreetAddress = "P.O. Box 206, 1152 Mauris Street", City = "Kailua", State = "HI", ZipCode = 65706 },
	        new Person { FirstName = "Channing", LastName = "Anderson", DateOfBirth = DateTime.Parse("04/09/80"), StreetAddress = "864-5375 Ac Rd.", City = "South Bend", State = "IN", ZipCode = 51828 },
	        new Person { FirstName = "Sacha", LastName = "Hopper", DateOfBirth = DateTime.Parse("09/03/70"), StreetAddress = "P.O. Box 264, 7373 Fusce St.", City = "Des Moines", State = "IA", ZipCode = 47058 },
	        new Person { FirstName = "Beck", LastName = "Watson", DateOfBirth = DateTime.Parse("10/21/72"), StreetAddress = "Ap #514-3009 Gravida Rd.", City = "Rochester", State = "MN", ZipCode = 68864 },
	        new Person { FirstName = "Xena", LastName = "Love", DateOfBirth = DateTime.Parse("09/27/89"), StreetAddress = "184-6157 Mus. Rd.", City = "Atlanta", State = "GA", ZipCode = 97094 },
	        new Person { FirstName = "Lunea", LastName = "Mccormick", DateOfBirth = DateTime.Parse("02/27/95"), StreetAddress = "P.O. Box 777, 8826 Et Rd.", City = "Des Moines", State = "IA", ZipCode = 32842 },
	        new Person { FirstName = "Walker", LastName = "Gray", DateOfBirth = DateTime.Parse("09/19/71"), StreetAddress = "P.O. Box 204, 4107 Vitae Street", City = "North Las Vegas", State = "NV", ZipCode = 46558 },
	        new Person { FirstName = "Angelica", LastName = "Peck", DateOfBirth = DateTime.Parse("10/06/75"), StreetAddress = "1144 Consectetuer St.", City = "Gresham", State = "OR", ZipCode = 65617 },
	        new Person { FirstName = "Bernard", LastName = "Mcintosh", DateOfBirth = DateTime.Parse("02/12/71"), StreetAddress = "706-670 Lobortis, Rd.", City = "Baton Rouge", State = "LA", ZipCode = 37922 },
	        new Person { FirstName = "Odette", LastName = "Wooten", DateOfBirth = DateTime.Parse("06/28/93"), StreetAddress = "Ap #528-3762 Nulla. Rd.", City = "Chesapeake", State = "VA", ZipCode = 54860 },
	        new Person { FirstName = "Teagan", LastName = "Black", DateOfBirth = DateTime.Parse("05/02/92"), StreetAddress = "P.O. Box 161, 4679 Ac Ave", City = "Olathe", State = "KS", ZipCode = 51778 },
	        new Person { FirstName = "Iona", LastName = "Kirk", DateOfBirth = DateTime.Parse("12/30/79"), StreetAddress = "3860 Egestas Street", City = "Springfield", State = "MA", ZipCode = 78075 },
	        new Person { FirstName = "Justina", LastName = "Gilliam", DateOfBirth = DateTime.Parse("10/28/77"), StreetAddress = "P.O. Box 539, 9621 Cursus, St.", City = "Kearney", State = "NE", ZipCode = 25947 },
	        new Person { FirstName = "Uriel", LastName = "Cortez", DateOfBirth = DateTime.Parse("03/11/90"), StreetAddress = "P.O. Box 795, 6949 Vitae Street", City = "Springfield", State = "IL", ZipCode = 29217 },
	        new Person { FirstName = "Rose", LastName = "Morris", DateOfBirth = DateTime.Parse("02/23/90"), StreetAddress = "Ap #992-8492 Libero St.", City = "Phoenix", State = "AZ", ZipCode = 85388 },
	        new Person { FirstName = "Chancellor", LastName = "Brooks", DateOfBirth = DateTime.Parse("03/09/73"), StreetAddress = "5629 Imperdiet St.", City = "San Francisco", State = "CA", ZipCode = 95318 },
	        new Person { FirstName = "Melanie", LastName = "Osborne", DateOfBirth = DateTime.Parse("02/22/78"), StreetAddress = "Ap #353-9153 Pharetra Rd.", City = "Henderson", State = "NV", ZipCode = 79947 },
	        new Person { FirstName = "Simon", LastName = "David", DateOfBirth = DateTime.Parse("11/27/76"), StreetAddress = "Ap #962-3720 Curabitur Avenue", City = "Honolulu", State = "HI", ZipCode = 82853 },
	        new Person { FirstName = "Thomas", LastName = "Freeman", DateOfBirth = DateTime.Parse("12/06/76"), StreetAddress = "3442 Pharetra. Rd.", City = "Bloomington", State = "MN", ZipCode = 47384 },
	        new Person { FirstName = "Uta", LastName = "Waters", DateOfBirth = DateTime.Parse("10/28/85"), StreetAddress = "3227 Vitae Ave", City = "Lawton", State = "OK", ZipCode = 40980 },
	        new Person { FirstName = "Flavia", LastName = "Cote", DateOfBirth = DateTime.Parse("07/09/78"), StreetAddress = "546-7815 Vitae, Rd.", City = "Nampa", State = "ID", ZipCode = 32232 },
	        new Person { FirstName = "Shelley", LastName = "Stephens", DateOfBirth = DateTime.Parse("05/15/88"), StreetAddress = "393-4248 Risus. Rd.", City = "Las Vegas", State = "NV", ZipCode = 86180 },
	        new Person { FirstName = "Meredith", LastName = "Wiggins", DateOfBirth = DateTime.Parse("06/07/90"), StreetAddress = "258-8364 Sit Rd.", City = "Annapolis", State = "MD", ZipCode = 11307 },
	        new Person { FirstName = "Ralph", LastName = "Stafford", DateOfBirth = DateTime.Parse("08/02/83"), StreetAddress = "P.O. Box 442, 8336 Non, Av.", City = "Norfolk", State = "VA", ZipCode = 15682 },
	        new Person { FirstName = "Ivor", LastName = "Graham", DateOfBirth = DateTime.Parse("05/18/71"), StreetAddress = "P.O. Box 936, 8900 Neque Ave", City = "Fort Collins", State = "CO", ZipCode = 97368 },
	        new Person { FirstName = "Hashim", LastName = "Hammond", DateOfBirth = DateTime.Parse("07/21/91"), StreetAddress = "P.O. Box 613, 2471 Sapien. St.", City = "Duluth", State = "MN", ZipCode = 15968 },
	        new Person { FirstName = "Diana", LastName = "Mcguire", DateOfBirth = DateTime.Parse("06/27/78"), StreetAddress = "8614 Blandit. St.", City = "St. Petersburg", State = "FL", ZipCode = 42386 },
	        new Person { FirstName = "Kyra", LastName = "Johnson", DateOfBirth = DateTime.Parse("06/01/81"), StreetAddress = "5340 Phasellus Road", City = "Essex", State = "VT", ZipCode = 49154 },
	        new Person { FirstName = "Sydnee", LastName = "Young", DateOfBirth = DateTime.Parse("06/13/94"), StreetAddress = "5525 Lectus Rd.", City = "Detroit", State = "MI", ZipCode = 58012 },
	        new Person { FirstName = "Shea", LastName = "Winters", DateOfBirth = DateTime.Parse("08/10/93"), StreetAddress = "4911 Eget Avenue", City = "Georgia", State = "GA", ZipCode = 47933 },
	        new Person { FirstName = "Maggie", LastName = "French", DateOfBirth = DateTime.Parse("05/01/72"), StreetAddress = "6000 Dolor Rd.", City = "Wichita", State = "KS", ZipCode = 17773 },
	        new Person { FirstName = "Lee", LastName = "Hoffman", DateOfBirth = DateTime.Parse("01/18/70"), StreetAddress = "Ap #516-2825 Praesent Av.", City = "Wilmington", State = "DE", ZipCode = 34456 },
	        new Person { FirstName = "Delilah", LastName = "Moore", DateOfBirth = DateTime.Parse("07/10/91"), StreetAddress = "P.O. Box 382, 1539 Nam Rd.", City = "Toledo", State = "OH", ZipCode = 33369 },
	        new Person { FirstName = "Colton", LastName = "Chandler", DateOfBirth = DateTime.Parse("05/08/82"), StreetAddress = "Ap #647-6307 At, Avenue", City = "West Valley City", State = "UT", ZipCode = 71138 },
	        new Person { FirstName = "Clark", LastName = "Stuart", DateOfBirth = DateTime.Parse("04/28/88"), StreetAddress = "Ap #390-9223 Lacus Rd.", City = "Flint", State = "MI", ZipCode = 47391 },
	        new Person { FirstName = "Axel", LastName = "Mcfadden", DateOfBirth = DateTime.Parse("02/04/70"), StreetAddress = "134-3929 Diam Ave", City = "Jonesboro", State = "AR", ZipCode = 71608 },
	        new Person { FirstName = "Lysandra", LastName = "James", DateOfBirth = DateTime.Parse("10/17/78"), StreetAddress = "769-1228 Sit Rd.", City = "Omaha", State = "NE", ZipCode = 86640 },
	        new Person { FirstName = "Maggie", LastName = "Russell", DateOfBirth = DateTime.Parse("04/25/80"), StreetAddress = "P.O. Box 429, 5667 Aliquam St.", City = "Akron", State = "OH", ZipCode = 54947 },
	        new Person { FirstName = "Heather", LastName = "Dennis", DateOfBirth = DateTime.Parse("03/21/88"), StreetAddress = "212-3893 Integer St.", City = "Independence", State = "MO", ZipCode = 11941 },
	        new Person { FirstName = "Guinevere", LastName = "Chen", DateOfBirth = DateTime.Parse("01/27/72"), StreetAddress = "Ap #520-7300 Tempus Av.", City = "Jacksonville", State = "FL", ZipCode = 91954 },
	        new Person { FirstName = "Kerry", LastName = "Cross", DateOfBirth = DateTime.Parse("01/11/79"), StreetAddress = "3313 Lacus Ave", City = "Rutland", State = "VT", ZipCode = 32635 },
	        new Person { FirstName = "Alden", LastName = "Ford", DateOfBirth = DateTime.Parse("04/25/84"), StreetAddress = "8632 Dictum St.", City = "Fayetteville", State = "AR", ZipCode = 72322 },
	        new Person { FirstName = "Quon", LastName = "Schneider", DateOfBirth = DateTime.Parse("01/27/70"), StreetAddress = "9555 Ante Rd.", City = "Joliet", State = "IL", ZipCode = 91223 },
	        new Person { FirstName = "Mufutau", LastName = "Tillman", DateOfBirth = DateTime.Parse("12/22/93"), StreetAddress = "P.O. Box 371, 7351 Curae; Ave", City = "Little Rock", State = "AR", ZipCode = 71921 },
	        new Person { FirstName = "Jason", LastName = "Guerra", DateOfBirth = DateTime.Parse("01/29/74"), StreetAddress = "Ap #358-669 Nulla. Avenue", City = "Idaho Falls", State = "ID", ZipCode = 60352 },
	        new Person { FirstName = "Pearl", LastName = "Roberson", DateOfBirth = DateTime.Parse("02/12/87"), StreetAddress = "Ap #375-9176 Pede. Avenue", City = "Tulsa", State = "OK", ZipCode = 55955 },
	        new Person { FirstName = "Ahmed", LastName = "Jacobs", DateOfBirth = DateTime.Parse("10/29/82"), StreetAddress = "776-2135 Nec, Ave", City = "Clarksville", State = "TN", ZipCode = 40770 },
	        new Person { FirstName = "Maggy", LastName = "Trevino", DateOfBirth = DateTime.Parse("10/18/93"), StreetAddress = "P.O. Box 314, 7557 Dui, Road", City = "West Valley City", State = "UT", ZipCode = 25458 },
	        new Person { FirstName = "Rogan", LastName = "Owens", DateOfBirth = DateTime.Parse("04/11/77"), StreetAddress = "212-5728 In Road", City = "Lawton", State = "OK", ZipCode = 55402 },
	        new Person { FirstName = "Karyn", LastName = "Stark", DateOfBirth = DateTime.Parse("07/31/80"), StreetAddress = "117-1148 Pretium Av.", City = "Hillsboro", State = "OR", ZipCode = 20382 },
	        new Person { FirstName = "Kirestin", LastName = "Graves", DateOfBirth = DateTime.Parse("06/05/81"), StreetAddress = "P.O. Box 551, 9632 Aliquet, St.", City = "Auburn", State = "ME", ZipCode = 82073 },
	        new Person { FirstName = "Jada", LastName = "Pope", DateOfBirth = DateTime.Parse("08/08/88"), StreetAddress = "Ap #220-8142 Tempor Street", City = "Missoula", State = "MT", ZipCode = 67820 },
	        new Person { FirstName = "Wyoming", LastName = "Bond", DateOfBirth = DateTime.Parse("03/31/77"), StreetAddress = "Ap #356-3066 Donec Rd.", City = "Virginia Beach", State = "VA", ZipCode = 53882 },
	        new Person { FirstName = "Fritz", LastName = "Nguyen", DateOfBirth = DateTime.Parse("07/31/74"), StreetAddress = "P.O. Box 769, 1020 Libero Avenue", City = "Casper", State = "WY", ZipCode = 50980 },
	        new Person { FirstName = "Rana", LastName = "Wagner", DateOfBirth = DateTime.Parse("10/20/74"), StreetAddress = "P.O. Box 208, 9352 Pellentesque Ave", City = "Chandler", State = "AZ", ZipCode = 85189 },
	        new Person { FirstName = "Slade", LastName = "Burton", DateOfBirth = DateTime.Parse("12/08/91"), StreetAddress = "947-3518 A Av.", City = "St. Petersburg", State = "FL", ZipCode = 36956 },
	        new Person { FirstName = "Thomas", LastName = "Huff", DateOfBirth = DateTime.Parse("03/13/75"), StreetAddress = "Ap #318-647 Lectus. Rd.", City = "Gary", State = "IN", ZipCode = 49107 },
	        new Person { FirstName = "Olympia", LastName = "Moses", DateOfBirth = DateTime.Parse("02/18/90"), StreetAddress = "P.O. Box 710, 7855 Nunc St.", City = "Overland Park", State = "KS", ZipCode = 60346 },
	        new Person { FirstName = "Chase", LastName = "Mcclure", DateOfBirth = DateTime.Parse("09/24/88"), StreetAddress = "P.O. Box 887, 9324 Sed Road", City = "Omaha", State = "NE", ZipCode = 37384 },
	        new Person { FirstName = "Erasmus", LastName = "Meyers", DateOfBirth = DateTime.Parse("02/13/87"), StreetAddress = "3039 Turpis Rd.", City = "Oklahoma City", State = "OK", ZipCode = 51993 },
	        new Person { FirstName = "Serena", LastName = "Potter", DateOfBirth = DateTime.Parse("07/06/85"), StreetAddress = "402-9409 Natoque Ave", City = "Indianapolis", State = "IN", ZipCode = 34451 },
	        new Person { FirstName = "Bevis", LastName = "Cameron", DateOfBirth = DateTime.Parse("12/12/94"), StreetAddress = "528-5432 Vivamus Ave", City = "Augusta", State = "ME", ZipCode = 83620 },
	        new Person { FirstName = "Isaiah", LastName = "Spears", DateOfBirth = DateTime.Parse("10/05/94"), StreetAddress = "P.O. Box 819, 3994 Consectetuer Street", City = "Bowling Green", State = "KY", ZipCode = 42748 },
	        new Person { FirstName = "Lewis", LastName = "Morales", DateOfBirth = DateTime.Parse("04/27/93"), StreetAddress = "Ap #407-2189 Duis Av.", City = "Tacoma", State = "WA", ZipCode = 92939 },
	        new Person { FirstName = "Sara", LastName = "Chapman", DateOfBirth = DateTime.Parse("07/31/72"), StreetAddress = "3885 Tellus St.", City = "Allentown", State = "PA", ZipCode = 76639 },
	        new Person { FirstName = "Hillary", LastName = "Shelton", DateOfBirth = DateTime.Parse("10/05/71"), StreetAddress = "674 Sit Rd.", City = "Memphis", State = "TN", ZipCode = 38111 },
	        new Person { FirstName = "Rachel", LastName = "Rhodes", DateOfBirth = DateTime.Parse("01/01/75"), StreetAddress = "Ap #152-260 Urna. Rd.", City = "Lowell", State = "MA", ZipCode = 39526 },
	        new Person { FirstName = "Todd", LastName = "Fields", DateOfBirth = DateTime.Parse("08/10/94"), StreetAddress = "4616 Sodales Rd.", City = "Oklahoma City", State = "OK", ZipCode = 74402 },
	        new Person { FirstName = "Daniel", LastName = "Pugh", DateOfBirth = DateTime.Parse("12/07/70"), StreetAddress = "Ap #481-6483 Lectus. Avenue", City = "Mesa", State = "AZ", ZipCode = 85151 },
	        new Person { FirstName = "Brett", LastName = "Banks", DateOfBirth = DateTime.Parse("10/08/91"), StreetAddress = "Ap #489-1768 Nullam Rd.", City = "Wyoming", State = "WY", ZipCode = 40650 },
	        new Person { FirstName = "Barry", LastName = "Petty", DateOfBirth = DateTime.Parse("09/10/88"), StreetAddress = "P.O. Box 986, 8682 Nec St.", City = "Boise", State = "ID", ZipCode = 96816 },
	        new Person { FirstName = "Brittany", LastName = "Singleton", DateOfBirth = DateTime.Parse("05/26/83"), StreetAddress = "Ap #367-872 Eu Street", City = "Indianapolis", State = "IN", ZipCode = 40019 },
	        new Person { FirstName = "Bree", LastName = "Hahn", DateOfBirth = DateTime.Parse("07/06/86"), StreetAddress = "P.O. Box 604, 5532 Sed Rd.", City = "Bloomington", State = "MN", ZipCode = 56431 },
	        new Person { FirstName = "Hayden", LastName = "Jarvis", DateOfBirth = DateTime.Parse("07/14/82"), StreetAddress = "4211 In, St.", City = "Boston", State = "MA", ZipCode = 78748 }
        };

        public IEnumerable<Person> Get()
        {
            return _people;
        }
    }
}
